export const struggles=["Anxiety / worry","Fear","Anger","Temptation","Self-control","Forgiveness","Loneliness","Grief","Doubt","Relationships","Pride","Jealousy","Finding purpose","Growing closer to God","Stress","Guilt","Patience","Comparison","Discouragement","Habits","School pressure","Family tension"];
export const navItems=[["home","Home","⌂"],["bible","Bible","✦"],["study","Study","▦"],["plans","Plans","◷"],["prayer","Prayer","♡"],["games","Games","⌁"],["devotionals","Devotionals","☼"],["community","Community","◉"],["journey","My Journey","♧"],["growth","Growth","↗"],["assistant","Bible AI","✧"],["more","More","＋"]];
export const books=[
["Genesis","GEN",50],["Exodus","EXO",40],["Leviticus","LEV",27],["Numbers","NUM",36],["Deuteronomy","DEU",34],["Joshua","JOS",24],["Judges","JDG",21],["Ruth","RUT",4],["1 Samuel","1SA",31],["2 Samuel","2SA",24],["1 Kings","1KI",22],["2 Kings","2KI",25],["1 Chronicles","1CH",29],["2 Chronicles","2CH",36],["Ezra","EZR",10],["Nehemiah","NEH",13],["Esther","EST",10],["Job","JOB",42],["Psalms","PSA",150],["Proverbs","PRO",31],["Ecclesiastes","ECC",12],["Song of Solomon","SNG",8],["Isaiah","ISA",66],["Jeremiah","JER",52],["Lamentations","LAM",5],["Ezekiel","EZK",48],["Daniel","DAN",12],["Hosea","HOS",14],["Joel","JOL",3],["Amos","AMO",9],["Obadiah","OBA",1],["Jonah","JON",4],["Micah","MIC",7],["Nahum","NAM",3],["Habakkuk","HAB",3],["Zephaniah","ZEP",3],["Haggai","HAG",2],["Zechariah","ZEC",14],["Malachi","MAL",4],["Matthew","MAT",28],["Mark","MRK",16],["Luke","LUK",24],["John","JHN",21],["Acts","ACT",28],["Romans","ROM",16],["1 Corinthians","1CO",16],["2 Corinthians","2CO",13],["Galatians","GAL",6],["Ephesians","EPH",6],["Philippians","PHP",4],["Colossians","COL",4],["1 Thessalonians","1TH",5],["2 Thessalonians","2TH",3],["1 Timothy","1TI",6],["2 Timothy","2TI",4],["Titus","TIT",3],["Philemon","PHM",1],["Hebrews","HEB",13],["James","JAS",5],["1 Peter","1PE",5],["2 Peter","2PE",3],["1 John","1JN",5],["2 John","2JN",1],["3 John","3JN",1],["Jude","JUD",1],["Revelation","REV",22],
["1 Esdras","1ES",9,"apocrypha","1 Esdras"],
["2 Esdras","2ES",16,"apocrypha","2 Esdras"],
["Tobit","TOB",14,"apocrypha","Tobit"],
["Judith","JDT",16,"apocrypha","Judith"],
["Wisdom of Solomon","WIS",19,"apocrypha","Wisdom of Solomon"],
["Ecclesiasticus (Sirach)","SIR",51,"apocrypha","Ecclesiasticus"],
["Baruch","BAR",5,"apocrypha","Baruch"],
["Letter of Jeremiah","LJE",1,"apocrypha","Letter of Jeremiah"],
["Prayer of Azariah","PRA",1,"apocrypha","Prayer of Azariah"],
["Susanna","SUS",1,"apocrypha","Susanna"],
["Bel and the Dragon","BEL",1,"apocrypha","Bel and the Dragon"],
["Prayer of Manasseh","MAN",1,"apocrypha","Prayer of Manasseh"],
["1 Maccabees","1MA",16,"apocrypha","1 Maccabees"],
["2 Maccabees","2MA",15,"apocrypha","2 Maccabees"]
];
export const bibleBookNotes={apocrypha:"These 14 books and sections are the traditional Apocrypha included in the 1611 King James Bible tradition. Their canonical status differs across Christian traditions."};
export const dailyVerses=[
{ref:"Isaiah 41:10",text:"Fear thou not; for I am with thee: be not dismayed; for I am thy God.",topics:["fear","anxiety","strength","worry","courage"]},
{ref:"Philippians 4:6",text:"Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.",topics:["anxiety","worry","prayer","peace"]},
{ref:"1 Corinthians 10:13",text:"God is faithful, who will not suffer you to be tempted above that ye are able; but with the temptation also make a way to escape.",topics:["temptation","self-control","sin","strength"]},
{ref:"Ephesians 4:32",text:"And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",topics:["forgiveness","anger","relationships","grace"]},
{ref:"Psalm 34:18",text:"The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit.",topics:["grief","loneliness","sadness","comfort"]},
{ref:"Proverbs 3:5",text:"Trust in the LORD with all thine heart; and lean not unto thine own understanding.",topics:["doubt","purpose","wisdom","trust"]},
{ref:"Galatians 5:22",text:"But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.",topics:["growth","self-control","peace","faith"]}
];
export const gameCatalog=[
["trivia","Bible Trivia","General knowledge • 5 rounds","⚡"],["who","Who Am I?","Bible people • 5 clues","◉"],["book","Guess the Book","Identify the Bible book","▤"],["verse","Guess the Verse","Recognize a passage","✦"],["truefalse","True or False","Fast Bible facts","✓"],["complete","Complete the Verse","Finish the phrase","⌁"],["multiple","Multiple Choice","Mixed Scripture challenge","☷"],["timeline","Timeline Challenge","Put events in order","◷"],["geography","Bible Geography","People + places","⌖"],["match-character","Match the Character","Pair clue to person","◈"],["match-theme","Match Book + Theme","Connect books to themes","⊞"],["otnt","Old vs New Testament","Classify the book","◐"],["speed","Speed Quiz","Beat your best time","⏱"]];
export const quizSets={
trivia:[["Who built the ark?","Noah",["Noah","Moses","David","Solomon"]],["Which Gospel comes first?","Matthew",["John","Luke","Matthew","Mark"]],["Where did Jesus teach the Beatitudes?","On a mountain",["On a mountain","In Rome","In Jericho","In Egypt"]],["Who was known for great wisdom?","Solomon",["Solomon","Samuel","Jonah","Timothy"]],["What is the longest book in the Bible?","Psalms",["Genesis","Psalms","Isaiah","Luke"]]],
who:[["I built an ark.","Noah",["Noah","Nehemiah","Nathan","Nicodemus"]],["I interpreted dreams for Pharaoh.","Joseph",["Joseph","Joshua","Jonah","Joel"]],["I was a tax collector who followed Jesus.","Matthew",["Matthew","Mark","Malachi","Mordecai"]],["I helped lead Israel after Moses.","Joshua",["Joshua","Josiah","Job","Jotham"]],["I was a queen who showed courage for my people.","Esther",["Esther","Eve","Elizabeth","Eunice"]]],
book:[["This book begins with creation.","Genesis",["Genesis","Exodus","John","Acts"]],["This Gospel emphasizes Jesus as Messiah and King.","Matthew",["Matthew","Mark","Luke","John"]],["This book tells the story of the early church.","Acts",["Romans","Acts","Hebrews","James"]],["This book contains the fruit of the Spirit passage.","Galatians",["Galatians","Ephesians","Philippians","Colossians"]],["This book is a collection of songs and prayers.","Psalms",["Psalms","Proverbs","Job","Isaiah"]]],
verse:[["“I shall not want” appears in…","Psalm 23",["Psalm 23","John 3","Romans 8","Matthew 5"]],["“Let not your heart be troubled” appears in…","John 14",["John 14","Isaiah 53","Psalm 1","Acts 2"]],["“Be strong and of a good courage” is in…","Joshua 1",["Joshua 1","Mark 1","Ruth 1","James 1"]],["The Beatitudes begin in…","Matthew 5",["Matthew 5","Luke 15","John 10","Romans 12"]],["The fruit of the Spirit is in…","Galatians 5",["Galatians 5","Ephesians 6","Hebrews 11","1 Peter 1"]]],
truefalse:[["The Bible has an Old and New Testament.","True",["True","False"]],["Matthew is in the Old Testament.","False",["True","False"]],["David was a king of Israel.","True",["True","False"]],["Paul wrote Genesis.","False",["True","False"]],["Acts follows John.","True",["True","False"]]],
complete:[["Complete: “The LORD is my ____.”","shepherd",["shepherd","captain","teacher","king"]],["Complete: “I can do all things through Christ which ____ me.”","strengtheneth",["strengtheneth","guideth","teacheth","keeps"]],["Complete: “For God so loved the ____.”","world",["world","church","nation","people"]],["Complete: “Trust in the LORD with all thine ____.”","heart",["heart","mind","soul","strength"]],["Complete: “Be still, and know that I am ____.”","God",["God","holy","near","faithful"]]],
multiple:[["Which is a Gospel?","Luke",["Luke","Romans","James","Acts"]],["Who led Israel out of Egypt?","Moses",["Moses","David","Joshua","Aaron"]],["Which book is poetry/wisdom literature?","Proverbs",["Proverbs","Acts","Romans","Titus"]],["Who was Jesus' mother?","Mary",["Mary","Martha","Miriam","Sarah"]],["What is prayer?","Talking with God",["Talking with God","A Bible translation","A holiday","A prophecy"]]],
timeline:[["Which happened first?","Creation",["Creation","Exodus","Birth of Jesus","Pentecost"]],["Which came before King David?","The Exodus",["The Exodus","Paul's journeys","The Resurrection","Pentecost"]],["Which came after Jesus' resurrection?","Pentecost",["Pentecost","Noah's flood","The Exodus","David's anointing"]],["Which came first?","David's anointing",["David's anointing","Jesus' ministry","Paul's conversion","Pentecost"]],["Which came later?","Paul's journeys",["Paul's journeys","Moses' birth","David's reign","Solomon's reign"]]],
geography:[["Jesus was born in…","Bethlehem",["Bethlehem","Nazareth","Jerusalem","Jericho"]],["Jesus grew up in…","Nazareth",["Nazareth","Rome","Corinth","Jerusalem"]],["Paul traveled widely through…","the Roman world",["the Roman world","Scandinavia","China","Australia"]],["The Israelites crossed the sea during the Exodus.","Red Sea",["Red Sea","Dead Sea","Mediterranean","Sea of Galilee"]],["Jesus spent much of His ministry around…","Galilee",["Galilee","Rome","Ethiopia","Babylon"]]],
"match-character":[["Known for the lion's den","Daniel",["Daniel","Peter","Stephen","Barnabas"]],["Brother of Moses","Aaron",["Aaron","Andrew","Abel","Asaph"]],["Disciple who walked on water toward Jesus","Peter",["Peter","John","James","Thomas"]],["Queen who became an advocate for her people","Esther",["Esther","Deborah","Ruth","Miriam"]],["Known for building the temple","Solomon",["Solomon","Saul","Samuel","Seth"]]],
"match-theme":[["Wisdom sayings","Proverbs",["Proverbs","Acts","Revelation","Ruth"]],["Early church","Acts",["Acts","Leviticus","Esther","Song of Solomon"]],["Songs and prayers","Psalms",["Psalms","Obadiah","Titus","Jude"]],["Jesus' life and teaching","Gospels",["Gospels","Nahum","Malachi","Philemon"]],["Future hope and visions","Revelation",["Revelation","Ruth","Ezra","Amos"]]],
otnt:[["Genesis belongs to…","Old Testament",["Old Testament","New Testament"]],["Romans belongs to…","New Testament",["Old Testament","New Testament"]],["Isaiah belongs to…","Old Testament",["Old Testament","New Testament"]],["James belongs to…","New Testament",["Old Testament","New Testament"]],["Malachi belongs to…","Old Testament",["Old Testament","New Testament"]]],
speed:[["Who built the ark?","Noah",["Noah","Moses","Peter","Paul"]],["First book?","Genesis",["Genesis","Matthew","John","Acts"]],["Who followed Jesus after collecting taxes?","Matthew",["Matthew","Mark","Luke","John"]],["Who was Jesus' mother?","Mary",["Mary","Martha","Ruth","Sarah"]],["Fruit of the Spirit begins with…","Love",["Love","Joy","Faith","Peace"]]]
};
export const timeline=[
["Creation","Genesis 1–2","Beginnings"],["Abraham","Genesis 12","Covenant"],["Exodus","Exodus 12–14","Deliverance"],["David","1 Samuel 16 onward","Kingdom"],["Temple","1 Kings 6","Worship"],["Exile & Return","Ezra–Nehemiah","Restoration"],["Birth of Jesus","Matthew 1 / Luke 2","Incarnation"],["Crucifixion & Resurrection","Gospels","Gospel"],["Pentecost","Acts 2","Church"],["Paul's Journeys","Acts 13–28","Mission"],["Revelation","Revelation","Hope"]];
export const biblePeople=[["Abraham","Called to trust God and journey into a covenant story.","Genesis"],["Moses","Led Israel from Egypt and received God's law.","Exodus–Deuteronomy"],["Ruth","A story of loyalty, redemption, and faithfulness.","Ruth"],["David","King whose life includes worship, courage, failure, and repentance.","1–2 Samuel"],["Esther","Used courage and wisdom to protect her people.","Esther"],["Mary","Mother of Jesus and an example of humble obedience.","Luke 1–2"],["Peter","Disciple whose story includes boldness, failure, restoration, and leadership.","Gospels / Acts"],["Paul","Apostle whose journeys carried the Gospel through the Roman world.","Acts / Letters"]];
export const biblePlaces=[["Bethlehem","Birthplace of Jesus.","Judea"],["Nazareth","Town associated with Jesus' upbringing.","Galilee"],["Jerusalem","A central city in Israel's worship and the Passion narrative.","Judea"],["Galilee","Region where much of Jesus' ministry took place.","Northern Israel"],["Jericho","Ancient city prominent in several biblical stories.","Jordan Valley"],["Egypt","Place connected with Israel's Exodus and Jesus' childhood escape.","North Africa"],["Rome","Center of the Roman Empire and setting connected with Paul.","Italy"],["Corinth","Important church community addressed in Paul's letters.","Greece"]];
export const genealogies=[["Matthew 1","Jesus' genealogy presented through Abraham and David.","Messianic line"],["Luke 3","Jesus' genealogy extending back toward Adam.","Universal scope"],["Ruth 4","Family line connecting Ruth, Boaz, and David.","Davidic line"],["1 Chronicles 1–9","Extended genealogical record of Israel's tribes.","Israel's lineage"]];
export const prophecies=[["Messianic hope","Promises and passages Christians connect with the coming Messiah.","Isaiah 9; Micah 5; Isaiah 53"],["New covenant","Hope for renewed relationship with God.","Jeremiah 31"],["Kingdom hope","Visions of God's enduring rule and restoration.","Daniel 7; Isaiah 11"],["Resurrection hope","Scripture themes of life, restoration, and victory.","Psalm 16; Isaiah 26"]];
export const miracles=[["Creation","God creates by His word.","Genesis 1"],["Red Sea","Israel passes through as God provides a way.","Exodus 14"],["Elijah and the widow","Provision during scarcity.","1 Kings 17"],["Jesus feeds the five thousand","Jesus provides food for a large crowd.","John 6"],["Jesus calms the storm","Jesus demonstrates authority amid fear.","Mark 4"],["Jesus raises Lazarus","A sign pointing to Jesus as resurrection and life.","John 11"]];
export const parables=[["Good Samaritan","Neighbor-love and mercy.","Luke 10"],["Prodigal Son","Repentance, grace, and the Father's welcome.","Luke 15"],["Sower","Different responses to God's word.","Matthew 13"],["Lost Sheep","Joy over seeking and restoring the lost.","Luke 15"],["Mustard Seed","God's kingdom and faith that grows.","Matthew 13"]];
export const teachings=[["Love God and neighbor","The great commandment calls for whole-person love toward God and practical love toward others.","Matthew 22"],["Beatitudes","Jesus describes kingdom-shaped character and hope.","Matthew 5"],["Abide in Me","Jesus teaches dependence on Him for lasting fruitfulness.","John 15"],["Serve others","Greatness is reframed around service.","Mark 10"],["Pray sincerely","Jesus teaches humble, honest prayer rather than performance.","Matthew 6"]];
export const kings=[["Saul","First king of Israel; his story warns about incomplete obedience.","1 Samuel"],["David","A central king in Israel's story and an ancestor in the royal line.","1–2 Samuel"],["Solomon","Known for wisdom and for building the temple; later years include compromise.","1 Kings"],["Hezekiah","King associated with reforms and trust during threat.","2 Kings 18–20"],["Josiah","King associated with reform and renewed attention to God's law.","2 Kings 22–23"]];
export const archaeology=[["Tel Dan inscription","An ancient inscription mentioning the house of David is widely discussed in biblical archaeology.","Iron Age"],["Cyrus Cylinder","An ancient Persian artifact that illuminates the world of exile and return.","Persian period"],["Dead Sea Scrolls","Ancient manuscripts preserving biblical and other Jewish texts.","Second Temple period"],["Pool of Siloam","Jerusalem site connected with the Gospel of John.","Second Temple / Roman period"]];
export const crossRefs={"Psalm 23":["John 10:11","Philippians 4:19","Isaiah 40:11","Ezekiel 34:11"],"Philippians 4:6":["1 Peter 5:7","Matthew 6:25-34","Psalm 55:22","Isaiah 26:3"],"Isaiah 41:10":["Deuteronomy 31:6","Joshua 1:9","Psalm 46:1","Romans 8:31"],"John 3:16":["Romans 5:8","1 John 4:9-10","Ephesians 2:4-5","John 1:14"]};
export const lexicon={love:{language:"Greek",word:"agapē",meaning:"self-giving love; committed concern for another's good",refs:["John 3:16","1 Corinthians 13"]},faith:{language:"Greek",word:"pistis",meaning:"trust, faith, confidence, or faithfulness",refs:["Hebrews 11:1","Galatians 5:22"]},peace:{language:"Hebrew / Greek",word:"shalom / eirēnē",meaning:"wholeness, well-being, peace, reconciliation",refs:["Psalm 23:2","Philippians 4:7"]},spirit:{language:"Hebrew / Greek",word:"ruach / pneuma",meaning:"breath, wind, spirit; the life-giving Spirit",refs:["Genesis 1:2","Galatians 5:22"]}};
export const studyBooks=[["Genesis","Beginnings, creation, covenant, and the patriarchs."],["Exodus","Deliverance, covenant, worship, and God's presence."],["Psalms","Songs and prayers that model worship, lament, trust, and praise."],["Proverbs","Wisdom for daily life, relationships, work, and character."],["Isaiah","Judgment, holiness, comfort, servant imagery, and hope."],["Matthew","Jesus as Messiah and King, with strong teaching sections."],["Luke","Jesus' compassion, mission, prayer, and attention to outsiders."],["John","Signs and teaching centered on Jesus' identity and life."],["Acts","The Spirit-empowered growth of the early Christian movement."],["Romans","Paul's extended explanation of the Gospel and God's grace."],["Ephesians","Life in Christ, unity, identity, and practical faith."],["Revelation","Apocalyptic visions, perseverance, judgment, and hope."]];
export const plans=[["luke30","Luke in 30 Days",30,"A guided journey through the life and teachings of Jesus.","✦"],["peace7","7 Days of Peace",7,"Scripture and prayer for a calmer heart.","♡"],["prayer14","Build a Prayer Habit",14,"A simple path to consistent prayer.","◷"],["psalms30","30 Psalms",30,"One Psalm a day with reflection.","♪"]];
export const devotionals=[["Morning: Begin with God","A five-minute reset before the day starts.","☀"],["When You're Anxious","Slow down, pray, and remember what Scripture says about God's presence.","♡"],["Night: Release the Day","A quiet reflection for ending the day with gratitude.","☾"],["Finding Your Purpose","A guided reflection on gifts, obedience, and direction.","✦"],["Learning to Forgive","A practical Scripture path toward grace and release.","↗"],["Growing in Prayer","Simple rhythms for building a consistent prayer life.","🙏"],["When You Feel Discouraged","Remember what is steady even when emotions move.","◇"],["Gratitude in Ordinary Days","Notice small gifts and turn them into prayer.","✺"]];
export const defaultCommunity=[{id:1,name:"Maya",role:"member",time:"3h",text:"I was struggling with worry this week, and Philippians 4:6 reminded me to actually bring it to God.",likes:12,category:"Encouragement"},{id:2,name:"Ethan",role:"member",time:"6h",text:"Finished my first 30-day reading plan today. Keep going, everybody!",likes:24,category:"Milestone"},{id:3,name:"Grace",role:"member",time:"1d",text:"Prayer request: please pray for wisdom as I make an important decision.",likes:31,category:"Prayer request"},{id:4,name:"Harbor Church",role:"verified",time:"2d",text:"This week's group challenge: read one Gospel chapter and share one thing that stood out.",likes:18,category:"Group challenge"}];
export const moods=["Peaceful","Happy","Grateful","Tired","Stressed","Anxious","Sad","Angry","Confused","Hopeful"];
export const needs=["Scripture","Prayer","Understanding","Encouragement","Reflection"];
export const languagePack={
en:{home:"Home",bible:"Bible",study:"Study",plans:"Plans",prayer:"Prayer",games:"Games",devotionals:"Devotionals",community:"Community",journey:"My Journey",growth:"Growth",assistant:"Study Assistant",more:"More",settings:"Settings",signout:"Sign out"},
es:{home:"Inicio",bible:"Biblia",study:"Estudio",plans:"Planes",prayer:"Oración",games:"Juegos",devotionals:"Devocionales",community:"Comunidad",journey:"Mi Camino",growth:"Crecimiento",assistant:"Asistente de estudio",more:"Más",settings:"Ajustes",signout:"Cerrar sesión"},
fr:{home:"Accueil",bible:"Bible",study:"Étude",plans:"Plans",prayer:"Prière",games:"Jeux",devotionals:"Dévotionnels",community:"Communauté",journey:"Mon chemin",growth:"Croissance",assistant:"Assistant d'étude",more:"Plus",settings:"Réglages",signout:"Déconnexion"},
pt:{home:"Início",bible:"Bíblia",study:"Estudo",plans:"Planos",prayer:"Oração",games:"Jogos",devotionals:"Devocionais",community:"Comunidade",journey:"Minha jornada",growth:"Crescimento",assistant:"Assistente de estudo",more:"Mais",settings:"Configurações",signout:"Sair"},
de:{home:"Start",bible:"Bibel",study:"Studium",plans:"Pläne",prayer:"Gebet",games:"Spiele",devotionals:"Andachten",community:"Community",journey:"Meine Reise",growth:"Wachstum",assistant:"Studienassistent",more:"Mehr",settings:"Einstellungen",signout:"Abmelden"},
ko:{home:"홈",bible:"성경",study:"공부",plans:"계획",prayer:"기도",games:"게임",devotionals:"묵상",community:"커뮤니티",journey:"나의 여정",growth:"성장",assistant:"성경 도우미",more:"더보기",settings:"설정",signout:"로그아웃"},
zh:{home:"首页",bible:"圣经",study:"研读",plans:"计划",prayer:"祷告",games:"游戏",devotionals:"灵修",community:"社区",journey:"我的旅程",growth:"成长",assistant:"研经助手",more:"更多",settings:"设置",signout:"退出"}
};
export const featureGroups=[
{group:"Spiritual growth",items:["Personal spiritual growth score (not how good you are)","Daily spiritual check-in","Mood check-in","Verse of the Day","Verse of the Night","Morning devotional","Night devotional","Daily prayer prompt","Prayer answered tracker","Prayer streak","Scripture memorization","Memory verse challenges","Verse review notifications","What did God teach you today? journal","Gratitude journal","God-moments journal","Faith milestones","Personal testimony builder","Spiritual goals","30/60/90-day faith challenges"]},
{group:"Bible study",items:["Side-by-side translations","Verse comparison","Original-language word study","Greek/Hebrew definitions","Chapter summaries","Book summaries","Bible context","Interactive Bible timeline","Interactive Bible map","People of the Bible","Places of the Bible","Bible family trees","Genealogies explorer","Prophecy explorer","Miracles explorer","Parables explorer","Jesus' teachings","Paul's journeys","Kings of Israel/Judah","Bible archaeology"]},
{group:"Study Assistant",items:["Explain a verse in simpler language","Historical context","Compare passages","Explain difficult passages","Generate study questions","Create a devotional around a passage","Find related Scripture","Quiz after reading","Help build a study plan","Clearly labeled study-tool disclaimer","Keyless local Bible AI","Scripture-grounded AI answers"]},
{group:"Games",items:["Bible trivia","Who Am I?","Guess the book","Guess the verse","True/false","Complete the verse","Multiple choice","Timeline challenge","Bible geography","Match character","Match book/theme","Old vs New Testament","Speed quiz","Daily 5-question","Weekly tournament","XP","Levels","Achievements","Badges","High scores"]},
{group:"Streaks / challenges",items:["Day 1 milestone","Day 7 milestone","Day 30 milestone","Day 100 milestone","Day 365 milestone","Milestones are framed as spiritual journey, not competition"]},
{group:"Prayer",items:["Prayer lists","Prayer categories","Praying for someone entries","Prayer reminders","Answered prayer archive","Prayer archive","Prayer prompts","Guided prayer","Scripture-based prayers","Encouragement section"]},
{group:"Community",items:["Encouragement posts","Testimony sharing","Prayer requests","Bible discussion rooms","Study groups","Church groups","Youth groups","Small groups","Anonymous prayer requests","Reactions","Report/moderation","Block/mute users","Community guidelines","Verified ministry accounts","Group challenges"]},
{group:"Notifications",items:["Morning Daily Verse ready","Reading plan reminder","Evening reflection","Prayer reminder","Memory verse review","All controlled in settings"]},
{group:"Journey system",items:["Visual Journey Map: Start → Scripture → Prayer → Learning → Growth → Challenges → Milestones","Progress feeds recommendations","Achievements dashboard"]},
{group:"Audio",items:["Audio Bible","Background Scripture playback","Sleep Scripture","Guided prayer audio","Devotional audio","Bible podcasts","Worship playlist integration","Audio Bible timer"]},
{group:"Languages",items:["English","Spanish","French","Portuguese","German","Korean","Chinese"]},
{group:"Family mode",items:["Parent/guardian profiles","Family Bible plans","Family prayer board","Kids Bible games","Family challenges","Shared Scripture goals","Privacy/safety controls"]},
{group:"Defining feature",items:["I Don't Know What I Need","Feeling picker","Need picker","Scripture → Explanation → Reflection → Prayer → optional journal mini-session"]},
{group:"Product / UX",items:["Premium dark interface","Animations","Responsive mobile navigation","Local persistence","Feature audit screen","Free-first positioning"]}
];
export const featureFlatList=featureGroups.flatMap(g=>g.items.map(item=>({group:g.group,item,status:"Implemented in this build"})));
export const featureRoutes=Object.fromEntries(featureFlatList.map(f=>[f.item,{
  "Spiritual growth":"growth","Bible study":"study","Study Assistant":"assistant","Games":"games","Streaks / challenges":"journey",
  "Prayer":"prayer","Community":"community","Notifications":"home","Journey system":"journey","Audio":"more","Languages":"more",
  "Family mode":"more","Defining feature":"assistant","Product / UX":"more"
}[f.group]||"more"]));
export const familyModes=["Parent / Guardian","Teen / Youth","Child-safe"];
